name: plugins
version: '${project.version}'
main: org.plugin.plugin.Plugin
api-version: 1.20

commands:
  die:
    description: die bitch
  cor:
    description: cor for all players

permissions:
  plugin.canMove:
    description: cant move
  plugin.can_add_cor:
    description: add cor